### ISSUE TITLE
Build a prototype using .NET Framework and Vue Js

### ISSUE THREAD

**Issue by saranshbhardwaj** [ARA-Trans/iAM#10]
- [x] Setup a basic application using Vue js and .Net Core
- [x] Going to implement Official Microsoft template for ASP .NET Core that uses Vue as its client-side framework.
- [x] Understand the different moving parts of the application in order to expand it.
- [x] Configure the application, such that it can be easily cloned from the GitHub by another developer.
- [x] Add a new client-side route and component, backed by a REST API on the server side
- [x] Understand the connection between Vue js and Controller. How are they interacting
- [x] Use Postman to make sure that the newly created REST APIs are working fine.
- [x] Fix the TypeScript warnings in Visual Studio to work properly with Typescript
- [x] Use InMemory Database and create a model layer to interact with the database
- [x] Create a new prototype using .Net Framework and Vue js
- [x] Enable app publishing for IIS
- [x] Get access to the write capabilities in the VM from local
- [x] Hook up Vue Js site with Web API in IIS
- [x] Make configuration changes to run VueJs app on IE
- [x] Configure the app to run in IE in production mode

**Comment by Chadley08** [comment]
SP - 5

**Comment by jakedw7** [comment]
Published API to VM
