### ISSUE TITLE
Scenarios UI - Main (v2)

### ISSUE THREAD

**Issue by ppator1** [ARA-Trans/iAM#128]
*Refer to mock-up for following changes/additions*
- [x] Play button in scenarios grids (starts a simulation on a scenario where a simulation has completed/has not been executed)
- [x] Reports button (launches a modal showing list of all downloadable reports)
- [x] Add the available reports in the modal popup
- [x] Add functionality to download multiple reports at a time

**Comment by ppator1** [comment]
SP - 5

**Comment by ppator1** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5cab53248c7a3a0011ca5d05)

**Comment by saranshbhardwaj** [comment]
SP-5
