### ISSUE TITLE
Prototype the attachment of the BridgeCare database to the app using EF

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#15]
- [x] Attach database to data model backend.
- [x] Create WebAPI for the model and call it from the VueJS frontend and show some output.
- [x] Connect local to Database present in VM
- [x] Solve the CORS error coming after connecting to the database
- [x] Remove dependencies for View part of MVC to make the API application lighter.

**Comment by jakedw7** [comment]
I have already done this.  What would you like to see in the demo app?
