### ISSUE TITLE
Create Scope editor criteria for the scenarios

### ISSUE THREAD

**Issue by saranshbhardwaj** [ARA-Trans/iAM#150]
- [x] Create the UI for the scope editor
- [x] Hook the UI with the scenarios
- [x] Add breadcrumb to the screen

**Comment by saranshbhardwaj** [comment]
SP-3

**Comment by ARA-Trans** [comment]
Remove the scope "tab" from the scenario editing screen. Add a Scope criteria editor into the analysis editor screen.
