### ISSUE TITLE
Create 'Committed Editor' for the Scenarios

### ISSUE THREAD

**Issue by saranshbhardwaj** [ARA-Trans/iAM#151]
- [x] Create the UI for committed editor
- [x] Hook up the editor with the scenarios
- [x] Add breadcrumb to the screen

**Comment by ARA-Trans** [comment]
Users need to be able to download the file that they have uploaded.

**Comment by ARA-Trans** [comment]
Users will upload a "standardized" (highway 23 report) to the committed projects page for a scenario. This will come as an Excel file.

**Comment by ARA-Trans** [comment]
SP - 3
