### ISSUE TITLE
EditAnalysis API

### ISSUE THREAD

**Issue by rbyrne2** [ARA-Trans/iAM#187]
- [x] Find Tables - Fill in Model to match web model
- [x] Add benefit variable dropdown to the UI.
- [x] Add service to populate benefits dropdown
- [x] Update EditAnalysis UI model to include the benefit variable property

**Comment by rbyrne2** [comment]
SP-2

**Comment by ARA-Trans** [comment]
Optimization type drop down - Exactly replicate the strings in the legacy analysis optimization drop down
Budget type drop down - Exactly replicate the strings in the legacy analysis budget drop down
Add Benefit variable drop down - A distinct list of all numeric attributes in the ATTRIBUTES_ table
Add Benefit weighting variable drop down - A distinct list of all numeric attributes in the ATTRIBUTES_ table
