### ISSUE TITLE
Implement the Committed projects parser and API calls.

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#215]
- [x] Define models.
- [x] Write APIs to parse and perform database operations

**Comment by AmrutaBorgaonkar** [comment]
SP-3

**Comment by AmrutaBorgaonkar** [comment]
[CommittedProjectsTemplate.xlsx](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5d07d423f954bf000f8df34c)
