### ISSUE TITLE
Run Simulation using Analysis engine

### ISSUE THREAD

**Issue by saranshbhardwaj** [ARA-Trans/iAM#22]
- [x] Create a Web API for this
- [x] Understand the existing functionality in the legacy application
- [x] Get the required dlls from legacy code to the current application
- [x] Update Vue Code. Fetch Network and Simulation details on button click
- [x] Add a generic Modal popup

**Comment by saranshbhardwaj** [comment]
SP-3

**Comment by rbyrne2** [comment]
I downloaded the legacy app from ARA-Trans/iAM-legacy, built and ran. Would like to  know where documents describing available test DB's I can try with connection strings.

**Comment by saranshbhardwaj** [comment]
You can find the connection string to connect to the server under the shared drive :  \\trans-il\User\Groups\Software\iAM\PennDOT
You want to connect to the Database name 'CHACO'  on this server.
