### ISSUE TITLE
Inventory UI API - Update for remaining columns

### ISSUE THREAD

**Issue by ppator1** [ARA-Trans/iAM#250]
Develop the Inventory UI API as defined in the API document (inventory.service.ts): https://app.swaggerhub.com/apis/ppatorno/iAM_Web_API/2.0.0-oas3
- [x] Front end implementation.
- [x] Back end implementation.

**Comment by ppator1** [comment]
SP - 1

**Comment by AmrutaBorgaonkar** [comment]
This involves updating apis with latest info on remaining data.

**Comment by AmrutaBorgaonkar** [comment]
[InsertForBRKey1_2_10.sql](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5d24cb6d62d9cb000fe36fb1)
[InventoryUpdateSchemaQuery.sql](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5d24cb6d3986b2000f18a421)
