### ISSUE TITLE
Investigate UI libraries for standardization of the UI

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#3]
- [x] We will probably use vuetify. Integrate it.
- [x] Investigate master-detail layout templates.
- [x] Meeting with jake for a walk through of existing RoadCare app
- [x] Add awesome-typescript to use typescript with vue

**Comment by ARA-Trans** [comment]
Yanbin has a good master detail template we can probably utilize, please discuss its implementation with her.

**Comment by Chadley08** [comment]
SP - 1
