### ISSUE TITLE
Implement Bridge Data tab report

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#30]
- [x] Meet with Jeff Davis to get information on where all the data for each report tab is coming from and DETERMINE HOW EACH FIELD IS BEING POPULATED
- [x] Implement the Bridge Data tab report.

**Comment by ARA-Trans** [comment]
Implement the report shown in teh "BridgeCareSummary Report JDW.xlsx" file.

**Comment by ARA-Trans** [comment]
[BridgeCare Summary Report JDW.xlsx](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5c4f6f5b4aff2900151b32a1)

**Comment by ARA-Trans** [comment]
SP - 8

**Comment by AmrutaBorgaonkar** [comment]
Done with current iteration task to figure out from where all places data is coming in the report.

Added task for next iteration.

**Comment by AmrutaBorgaonkar** [comment]
This is done except a filter row after headers. Next iteration will be checking to speed up excel generation right now its taking around 4 mins to get approx. 53 Mb of excel report.

**Comment by AmrutaBorgaonkar** [comment]
This is done.

**Comment by AmrutaBorgaonkar** [comment]
Questions for Jeff:
1. For Poor On/Off Rate column: Formula (prev yr SD == "Y")?(curr yr SD=="N")?"Off":"On":"--"
It is same for all years except 2018(previous year), is it typo or meant to different.

2. Observed below in the macro, is the hard coding to be applied only to below data? 
Func_Class='12' where BRKey=8356") Func_Class='16' where BRKey=45700") Func_Class='01' where BRKey=29077") Func_Class='06' where BRKey=55748")

**Comment by AmrutaBorgaonkar** [comment]
Marking it resolved. I will be checking above questions with Jeff and addressing those as a part of active feature/next iteration feature.

**Comment by jefdavis** [comment]
Amruta: 
1. The formula is correct has written 2018 is the base data and 2019 is the start of the analysis year
2 . You can remove the hard coding  for the BRkeys you have listed

**Comment by AmrutaBorgaonkar** [comment]
Sure, I will keep same formula for 2018 as per Excel then and ignore hard coding from Macro. Thank you Jeff.
