### ISSUE TITLE
Priorities as a library

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#303]
Add library functionality for the Prioritization UIs:
-each tab (priorities, targets, deficients) will be its own separate library
-match the functionality of the other library editor UIs
-update mongo db with new entities for priorities, targets, and deficients
- [x] Add mongoDB model
- [x] Add mongoDB controller
- [x] Add mongoDB routes
- [x] Add Vue PriorityLibrary model
- [x] Update Vue Priority & PriorityFund models
- [x] Add server PriorityLibrary model
- [x] Update server Priority & PriorityFund models
- [x] Update Priority API
- [x] Update PrioritiesTab.vue component
- [x] Update priority.service.ts
- [x] Update priority.module.ts

**Comment by ppator1** [comment]
SP - 8
