### ISSUE TITLE
Server side logging for errors/info messages/exceptions for C# API application

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#304]
Moving this to new issues since I feel like we need to implement logs in case our users experience errors. This way if the server is not providing a detailed message, we can have the users send us the log file created which should have more details about bugs.
- [x] Select a library for Logging and configure it in C# API application
- [x] Log the errors in the log file, which was created during configuration

**Comment by ARA-Trans** [comment]
We should be putting unit tests in place for NodeJS

As we begin the refactoring process for the rollup and analysis, we will write appropriate unit tests.

**Comment by ppator1** [comment]
SP - 3
