### ISSUE TITLE
Fix issue with report generation using dynamic simulation variables

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#328]
- [x] Check if SIMULATION_VARIABLES used in report exists for current Simulation. Throw error in case not found.

**Comment by ARA-Trans** [comment]
SP - 3

**Comment by AmrutaBorgaonkar** [comment]
Note: 
Report is tightly bound to a set of SIMULATION_VARIABLES and has formulae dependent on those for other cells and other worksheets as well.
