### ISSUE TITLE
Implement the Inventory UI

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#39]
- [x] Implement Section model to drive data grid
- [x] Implement Section Id dropdown
- [x] Implement attribute filter (add/remove section attributes in grid)
- [x] Implement year filter (add/remove year columns showing section attribute values for that year)
- [x] Implement a section bridge-attribute data grid component
- [x] Implement selected section logic
- [x] Implement attribute filter logic
- [x] Implement year filter logic
- [x] Implement google maps integration
- [x] Implement section images

**Comment by ARA-Trans** [comment]
SP - 8

**Comment by ppator1** [comment]
INVENTORY VIEW MOCKUP
![inventory_ui](https://user-images.githubusercontent.com/16454404/52375648-0fad1200-2a58-11e9-8d02-e59d1c0a443d.jpg)

**Comment by rbyrne2** [comment]
Notes on implementation: /chads email
-	This will be the first page an administrative user sees after logging in and selecting the “Inventory” route.
-	For the GIS – please use a google map placeholder for now. No special features (no marker, etc.).
-	For the pictures, please load some stock photos for now. We’ll want to eventually integrate with PennDOTs data systems to pull in data based on the bridge ID.
-	Data associated with the grid is all pulled from the RoadCare database.
