### ISSUE TITLE
New graphics need to be added to the application

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#391]
- [ ] Add PennDOT Logos
- [ ] Add BridgeCare Logos
- [x] Add banner logos to landing pages and logout page

**Comment by ARA-Trans** [comment]
@jdavisDOT and Justin Bruener will provide mockups for locations of PennDOT logos.

**Comment by jakedw7** [comment]
Added need to add new graphics provided by Bruner to the application

**Comment by ARA-Trans** [comment]
@jdavisDOT Jeff, have these been sent yet? I can't find them in my email. If you have sent them, would you mind sending them over again? Sorry for the trouble!

**Comment by ARA-Trans** [comment]
See #418 for logos.
