### ISSUE TITLE
"Cash Flow" enhancements

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#408]
- [x] Flowchart of cash flow interface
- [x] Mockup UI for system
- [x] Implement system in analysis
- [x] Implement UI

- [x] Mockup UI for web application
- [x] Implement UI for web application

**Comment by ARA-Trans** [comment]
Cash flow answers the question, "If you do not spend all the money in a given year what happens to the money?"

We will need to think about and develop a way to spread the cost of the projects that are selected over a prescribed number of years.

@jdavisDOT and Justin will provide mockups of what the user interaction they want to have will provide. The development team will then discuss with them options and recommend a course of action.

**Comment by jakedw7** [comment]
[Cash Flow Budgeting for BridgeCare.docx](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5db89310f864f8000f80ffb8)

**Comment by jakedw7** [comment]
Just added the approved version of the cash flow feature description to my comment above.
