### ISSUE TITLE
Create a BridgeCare and iAM logos.

### ISSUE THREAD

**Issue by Chadley08** [ARA-Trans/iAM#418]
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e14c71f05746d0010cc97c3)
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e14c71fe83aa60010ab3fa3)
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e14c71f553d4500116d7597)

**Comment by jakedw7** [comment]
BridgeCare logos have been provided by Bruner

**Comment by ARA-Trans** [comment]
At one point we had discussed a "landing page" for the users. Should we move forward with implementing it and what should it look like? (Putting this here as I assume some of these logos are relevant to the landing page).

Additionally, where should these logos be used in the application? @jdavisDOT can we discuss during the review?

**Comment by ARA-Trans** [comment]
If further logos need to be added to pages, Justin/Jeff can tell us where to put them. Leaving this card in the backlog until this has happened.
