### ISSUE TITLE
Jobs queue for the analysis runs

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#440]

**Comment by rummelsworth** [comment]
This sounds a lot like what I was asked to investigate this afternoon, so I'm reopening, and there's a branch `vnext/440` with the candidate implementation so far.

**Comment by rummelsworth** [comment]
@johnimalmberg We can touch base tomorrow about the "callsite integration" of the process-based queue service I threw together. After that, I think you can take over.
