### ISSUE TITLE
Priorities with Year = 0

### ISSUE THREAD

**Issue by jakedw7** [ARA-Trans/iAM#488]
Priorities should not be set to year = 0.  These should be set to null.  When Year is null, it applies to all years.  The other way to handle this would be to set year = "All" but that could cause additional UI issues/validation requirements.

**Comment by ARA-Trans** [comment]
@saranshbhardwaj Can you confirm that this has been resolved?

Is this the UI interaction that we want? (0 = All Years) @jdavisDOT?

**Comment by jakedw7** [comment]
@saranshbhardwaj Per @jdavisDOT this is how they want it to work
