### ISSUE TITLE
Set up the iAM server for development.

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#5]
- [x] Setup VM
- [x] Get IT approval
- [x] Setup IIS
- [x] Setup MS SQL
- [x] Load current RoadCare database
- [x] Get SQL Server Access to remote VM

**Comment by jakedw7** [comment]
Established server at 40.121.5.125. Waiting on IT to allow access

**Comment by jakedw7** [comment]
IT has allowed RDP but not SQL.  Chad, I am adding you to this as you need to get back to Chris Gabbert at IT on opening up the SQL server port in the ARA firewall.  Let me know when that is done

**Comment by Chadley08** [comment]
Thanks Jake. I've seen the emails but haven't had a chance to reply yet. I
will try to do that today.

**Comment by Chadley08** [comment]
SP - 1
