### ISSUE TITLE
Make all criteria fields editable

### ISSUE THREAD

**Issue by jakedw7** [ARA-Trans/iAM#500]
- [ ] Check with Chad and Paul on ability to implement editable criteria

**Comment by jakedw7** [comment]
Per Paul, it is possible but the parser is very picky about the criteria.  Jake suggested putting a switch on the box that turns off editor when the user is entering text directly.  Paul thinks that the validation is already done when trying to save.

**Comment by ARA-Trans** [comment]
Allowing users to directly input criteria will likely cause the parsing to fail at some point due to invalid user input. Please confirm this is what we actually want to do.

If users fail validation, they will have to find the error in the criteria editor themselves and resolve it.

**Comment by ARA-Trans** [comment]
#503 related
