### ISSUE TITLE
Add ability to have multiple lines for criteria

### ISSUE THREAD

**Issue by jakedw7** [ARA-Trans/iAM#502]
- [x] Create mockup of multiple criteria lines
- [x] Review with Jake/Justin/Jeff
- [x] Implement new UI for criteria editor
[Criteria Editor Mockups.pdf](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e32e2e9fd90a600107e3b03)

- [x] Get estimate for implementing UI including schema changes

**Comment by ARA-Trans** [comment]
@jwalterARA Please provide a mockup of this work item.

**Comment by ARA-Trans** [comment]
Chad, please provide a mockup of this screen.

**Comment by jakedw7** [comment]
Added initial mockup for commentary by client

**Comment by jakedw7** [comment]
Got OK from client.  Sent to Paul for review
