### ISSUE TITLE
Authorization - Detailed Role settings, basic scenario ownership, User Criteria

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#513]
[Permission Matrix PennDOT with intermediate step(1).xlsx](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e14ae8ae83aa60010ab3c4a)

Scenario Ownership:
- [x] Add ownership to scenarios
- [x] Add ownership to all libraries except remaining life limit libraries

Misc:
- [x] Allow users to delete libraries (required before implementing role permissions for library deletion)
- [x] Provide real-time updates when users delete libraries

Detailed Role settings:
- [x] Restrict visibility of scenarios based on user role and scenario ownership
- [x] Restrict visibility of libraries based on user role and library ownership
- [x] Restrict modification and deletion of libraries based on user role and library ownership
- [x] Restrict scenario modification and deletion based on user role and scenario ownership
- [x] Update Remaining Life Limit permissions based on #578
- [x] Restrict access to cash flow based on #578

User Criteria
- [x] Create user interface for administrators to modify user criteria
- [x] Create vuex store for user criteria data
- [x] Create service for interfacing with the C# user criteria API
- [x] Create C# user criteria API controller, DAL, model
- [x] Create SQL table and matching Entity class for user criteria settings
- [x] Create migration script for the new SQL table
- [x] Restrict visibility of inventory data based on user criteria filters
- [x] When simulations are run, filter the inventory data they can access based on user criteria filter

**Comment by ARA-Trans** [comment]
Ensure that business partners can log in to the iAM BridgeCare system.

**Comment by ARA-Trans** [comment]
Adding more specific role-based authorization to every API endpoint in NodeJS and C#. Adds ownership/sharing to scenarios pending responses from PennDOT.

Adds user criteria based access to inventory data.

Adds delete functionality for libraries.

**Comment by johnimalmberg** [comment]
Attached is the spreadsheet of authorization requirements sent by Jake Walter on 11/18/2019, detailing the specific permissions that must be available to each role.

**Comment by johnimalmberg** [comment]
Some clarification is needed for the following items:

When a user logs into the system for the first time, and no administrator has assigned criteria filters to them, what inventory items should they be able to access by default?

What is the intended effect of sharing a scenario? Is a scenario shared with specific other users, or is sharing simply a matter of making the scenario public or private? 
In the first case, does this create a new copy of the scenario for the other user, or do both users gain equal access to the same exact scenario?
Which user's criteria filter is applied when running a shared scenario?

What permissions should be applied to the scenario Remaining Life Limit page?
The spreadsheet specifies that only administrators can interact with remaining life limit libraries, but does not specify anything regarding a scenario's remaining life limits.

When cash flow is added, what permissions should users have for it?

The spreadsheet also indicates the need for a new page, "News," and the permissions associated with it. A mockup of what this page should look like is needed.
