### ISSUE TITLE
BridgeCare on PennDOT Server not Spending Money

### ISSUE THREAD

**Issue by jdavis360** [ARA-Trans/iAM#520]
Try to run a scenario with BridgeCare that is hosted on the PennDOT server. I setup the scenario as normal when I ran the scenario and the web site said it ran to success.  Then downloaded the "Summary Report" the report is showing that no money was spent.  When I ran the same exact scenario on iAm- Deploy the "Summary Report" is showing that money is being spent.

**Comment by ARA-Trans** [comment]
Caused by issue #488

**Comment by jakedw7** [comment]
@ARA-Trans:  Has this been fixed by the #488 fix then?
