### ISSUE TITLE
Analysis engine issue

### ISSUE THREAD

**Issue by jdavis360** [ARA-Trans/iAM#521]
I created the scenario called "Matt 11-12-19". In this scenario setup a 12 year analysis but only gave it funding for 5 years.  When I run the scenario the site cranks through years 1-5 not a problem but when it year 6 the web just stops.

**Comment by ARA-Trans** [comment]
Caused by issue #488

**Comment by jakedw7** [comment]
@ARA-Trans Has this been addressed as part of the #488 fix then?
