### ISSUE TITLE
Date modified in the Scenarios Screen not updating

### ISSUE THREAD

**Issue by jdavis360** [ARA-Trans/iAM#524]
I was updating a scenario I created 2 weeks ago.  After I saved the scenario when back to the Scenario screen and noticed the Date last modified was showing the date I created the scenario.
- [x] Change code in vuejs to send the correct information about the modified date
- [x] Accept the new information in Nodejs application
- [x] Change query to update the mongo db with the updated date
- [x] Send back the updated date information from nodejs to vuejs

**Comment by saranshbhardwaj** [comment]
When a user run a simulation, the last modified date should be updated
