### ISSUE TITLE
On successful login, users without BAMS roles should be redirected to a new information page.

### ISSUE THREAD

**Issue by johnimalmberg** [ARA-Trans/iAM#556]
Currently, the user receives a success message, but cannot access any secured API endpoints.
- [x] Detect users without roles
- [x] Create a new landing page for users without roles
- [x] Redirect those users to that page

The above tasks were implemented with the resolution of card #435

- [x] Acquire non-placeholder email for requesting access to the app

**Comment by johnimalmberg** [comment]
Some users have ESEC accounts for apps other than our bridgecare app. The app should detect these users and show them a page which tells them they do not have access.

**Comment by ARA-Trans** [comment]
Create a mockup page to send to Justin for revision.
