### ISSUE TITLE
Prevent socket.io's polling fallback when websockets fail.

### ISSUE THREAD

**Issue by johnimalmberg** [ARA-Trans/iAM#563]
When the websocket connection fails, the app should not begin polling.

Additionally, an error / warning message should be shown to the user.
- [x] Identify where the changes need to be made
- [x] Disable the polling mechanism when websocket fails

**Comment by saranshbhardwaj** [comment]
If websocket connection fails, the polling mechanism should not kick in. The website should again try to establish the websocket connection
