### ISSUE TITLE
Add server side logging for the legacy application

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#565]
- [x] Find a library to fast track logging process
- [x] Install the library
- [x] Configure it for the application
- [ ] Implement it's features to catch the errors
- [ ] Format the log file to increase the readability of it

**Comment by saranshbhardwaj** [comment]
If any error occurs while running rollup or simulation, it should be logged in a log file

**Comment by ARA-Trans** [comment]
We are keeping the server side logging branch open (not deleting it). We will not merge it into master at this time as it may affect performance. If we need to reintroduce the logging, we can cherry-pick it from the associated branch.
