### ISSUE TITLE
Updating BridgeCare Inventory Data

### ISSUE THREAD

**Issue by jdavis360** [ARA-Trans/iAM#566]
Updating the bridge condition and inventory data.  The file are attached
[BridgeCare web Inventory Table_01_06_20.xlsx](https://github.com/ARA-Trans/iAM/files/4031731/BridgeCare.web.Inventory.Table_01_06_20.xlsx)
[Operating Rating vs Inventory Rating Data asof 01_06_19.xlsx](https://github.com/ARA-Trans/iAM/files/4031733/Operating.Rating.vs.Inventory.Rating.Data.asof.01_06_19.xlsx)

- [x] Change the column names in the excel file to match the names in the data table
- [x] Convert excel files to text delimiter
- [x] Import both of the text delimiter files in the database, in two separate tables
- [x] Write SQL queries to join newly created tables and insert data in the main table
- [x] Test few scenarios to make sure there is no corrupt data.

**Comment by saranshbhardwaj** [comment]
User should see the new data on the Inventory page
