### ISSUE TITLE
Mockup of equation editor UI changes to dev team

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#573]
- [x] Create mockup
- [x] Review with dev team
- [x] Review with PennDOT personnel
[Performance Model Mockups.pdf](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e32d30020850c001025b7b5)

**Comment by jakedw7** [comment]
Added mockups.  Will discuss with PennDOT.

**Comment by jakedw7** [comment]
Got the OK on this from PennDOT.  Further comments from the Dev Team?
