### ISSUE TITLE
Hook up Azure AD B2C with VueJS to handle authentication

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#6]
- [x] Review Azure B2C documentation
- [x] Decide between B2C or Azure AD authentication
- [x] Set up the Azure application services (for authentication)
- [x] Test
- [x] Learning difference between Azure AD B2C and Azure AD B2B
- [x] Learn about Vue-adal library to implement Azure authentication service in the VueJs application
- [x] Configure localhost on the Azure portal B2C
- [x] Use Msal.js to integrate VueJs app with Azure B2C
- [x] Make additional configurations to make things work on IE
- [x] Use Vuetify for an acceptable design.
- [x] Create another Application on Azure AD B2C for IIS
- [x] Get SSL certificate
- [x] Stop application from logging out every time user refreshes the page
- [x] Create password reset policy and integrate it in Vuejs app
- [x] Handle the Azure errors when a user clicks cancel button

**Comment by saranshbhardwaj** [comment]
The user needs to be able to login or cancel the operation.

**Comment by Chadley08** [comment]
B2C tenant created at aratranstest.onmicrosoft.com. See https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant on how to use

**Comment by Chadley08** [comment]
SP - 8

**Comment by jakedw7** [comment]
Will need to do this on the Vue app first.  Is anyone else going to review the B2C docs?

**Comment by Chadley08** [comment]
I believe @saranshbhardwaj  will review them.
