### ISSUE TITLE
Implement Inventory UI alterations per PennDOT

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#60]
There are some changes the client has asked for regarding the Inventory UI.

1) Add two selects for selecting a section with some kind of toggle to show/activate one select over the other
1a) Select: br key, Select: bms id (update models accordingly)
2) Possibly removing attribute & year select filters (pending meeting with client on how users currently see inventory data)
3) Split the google maps into two (1 half shows the actual map, the other half shows a street view if applicable)
- [x] Add toggle to swtich between bms id & br key selects
- [x] Add selects for bms id & br key
- [x] Update models to match shape of data
- [x] Update view based on clients' changes/requirements (reference mock-ups)

**Comment by ARA-Trans** [comment]
SP - 5

**Comment by ARA-Trans** [comment]
SP - 5

**Comment by ARA-Trans** [comment]
SP - 5

**Comment by ARA-Trans** [comment]
SP - 5

**Comment by ARA-Trans** [comment]
SP - 5

**Comment by ppator1** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5c8a67bef9212a000fd23167)
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5c8a67bff9212a000fd23170)
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5c8a67bff9212a000fd2316d)
![image](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5c8a67bff9212a000fd2316a)
