### ISSUE TITLE
Add Clone Simulation to Vue App

### ISSUE THREAD

**Issue by johnimalmberg** [ARA-Trans/iAM#630]
Allow users to clone their own simulations, and simulations that have been shared with them.

Clones of shared simulations should use the user criteria of the user who cloned the simulation, not its original creator.
- [x] Add C# api endpoint to duplicate an existing scenario
- [x] Create vue interface for cloning scenarios
- [x] Test to ensure that cloned scenarios run properly, producing identical results to their base scenario

Cloned scenarios are running properly on iam-deploy, but producing incorrect results on local builds, despite using the same database. - This was due to an undiscovered issue unrelated to cloning, which is resolved in this branch.

**Comment by jakedw7** [comment]
Jake checked this.
