### ISSUE TITLE
Existing committed projects cannot be overwritten

### ISSUE THREAD

**Issue by johnimalmberg** [ARA-Trans/iAM#658]
When uploading committed projects for a simulation, new commitments can be added, but attempted modifications to existing commitments fail.

The new intended behavior is that when a user uploads commitments, all existing commitments for that scenario are deleted before the new commitments are added.

**Comment by jakedw7** [comment]
Not overwriting old committed projects.  See attached.  When I uploaded, I just changed the years to 2021[CommittedProjects (10).xlsx](https://app.gitkraken.com/api/glo/boards/5be1aa981fc3b8000f7d72ea/attachments/5e616f03916ce500128413f3)
