### ISSUE TITLE
Default the equation editor to the full time range.

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#671]
- The full time range should be displayed in the chart
- Remove pagination
- Check performance for large time periods (300 years).
- Maybe set a max value allowed at (500 years?).
- Change "Attribute" to "Condition" on the y-axis of the graph.
- **Discuss Time in Rating changes with Jake.**
  - Use integer values for the attribute.
  - time-in-rating values are non-cumulative, but the piecewise values are
    - e.g., we have TIR values of (9,3) & (8,2) which is the condition rating to a number of years (rating of 9 for 3 years)
       - to get the piecewise values we start at (0,10) then into (3,9) because time of 0 years plus 3 years is 3
       - for the next TIR value, the piecewise value would be (5,8) which is the previous value's 3 years added to the current value of 2 years
- Change the x-axis label tick marks to always show ten tick marks.
- [x] Remove pagination
- [x] Show full time range
- [x] Change 'Attribute' to 'Condition'
- [x] Implement TIR conversion from piecewise values & vice versa
- [x] Set chart zoom to max

**Comment by ARA-Trans** [comment]
SP - 8

**Comment by jakedw7** [comment]
I would comment that you may need to change the X AXIS for the time in rating plot if you are changing it
