### ISSUE TITLE
Check the Epoxy/Joint Glands/Coatings Criteria

### ISSUE THREAD

**Issue by ppator1** [ARA-Trans/iAM#681]
A feasibility criteria string for the Epoxy/Joint Glands/Coatings treatment under treatment library "Default Treatments" is causing issues with the criteria editor parsing.

[BRIDGE_TYPE]=|B| AND [DECK_AREA]>=|28500| AND [YEAR_BUILT]>=|1983| AND [ADTTOTAL]<|25000| AND [DECK_SEEDED]>=7 AND ([DECK_DURATION_N]>=5  AND [DECK_SEEDED]>= [PREV_DECKSEED])  AND [SUB_SEEDED]>=5.5 AND [SUP_SEEDED]>=5.5 AND ([DECKSURF_TYPE]=|1| OR [DECKSURF_TYPE]=|5|) AND [WS_SEEDED]>=|6|  AND [LATX_CNT]=0 AND [P3]=|0| AND [BRIDGE_TYPE]=|B| AND ([BUS_PLAN_NETWORK]=|1| OR [BUS_PLAN_NETWORK]=|T|) AND [DECK_AREA]<|28500| AND [YEAR_BUILT]>=|1983| AND [LENGTH]>=|50| AND [ADTTOTAL]<|25000| AND [DECK_SEEDED]>=7 AND ([DECK_DURATION_N]>=5  AND [DECK_SEEDED]>= [PREV_DECKSEED])  AND [SUB_SEEDED]>=5.5 AND [SUP_SEEDED]>=5.5 AND ([DECKSURF_TYPE]=|1| OR [DECKSURF_TYPE]=|5|) AND [WS_SEEDED]>=|6|  AND [LATX_CNT]=0 AND [P3]=|0| AND [BRIDGE_TYPE]=|B| AND ([BUS_PLAN_NETWORK]=|2| OR [BUS_PLAN_NETWORK]=|H|) AND [DECK_AREA]<|28500| AND [YEAR_BUILT]>=|1983| AND [LENGTH]>=|50| AND [ADTTOTAL]<|25000| AND [DECK_SEEDED]>=7 AND ([DECK_DURATION_N]>=5  AND [DECK_SEEDED]>= [PREV_DECKSEED])  AND [SUB_SEEDED]>=5.5 AND [SUP_SEEDED]>=5.5 AND ([DECKSURF_TYPE]=|1| OR [DECKSURF_TYPE]=|5|) AND [WS_SEEDED]>=|6|  AND [LATX_CNT]=0 AND [P3]=|0| AND [BRIDGE_TYPE]=|B| AND [BUS_PLAN_NETWORK]=|3| AND [DECK_AREA]<|28500| AND [YEAR_BUILT]>=|1983| AND [LENGTH]>=|50| AND [ADTTOTAL]<|25000| AND [DECK_SEEDED]>=7 AND ([DECK_DURATION_N]>=5  AND [DECK_SEEDED]>= [PREV_DECKSEED])  AND [SUB_SEEDED]>=5.5 AND [SUP_SEEDED]>=5.5 AND ([DECKSURF_TYPE]=|1| OR [DECKSURF_TYPE]=|5|) AND [WS_SEEDED]>=|6|  AND [LATX_CNT]=0 AND [P3]=|0| AND [BRIDGE_TYPE]=|B| AND ([BUS_PLAN_NETWORK]=|4| OR [BUS_PLAN_NETWORK]=|L| OR [BUS_PLAN_NETWORK]=|D| OR [BUS_PLAN_NETWORK]=|N|) AND [DECK_AREA]<|28500| AND [YEAR_BUILT]>=|1983| AND [LENGTH]>=|50| AND [ADTTOTAL]<|25000| AND [DECK_SEEDED]>=7 AND ([DECK_DURATION_N]>=5  AND [DECK_SEEDED]>= [PREV_DECKSEED])  AND [SUB_SEEDED]>=5.5 AND [SUP_SEEDED]>=5.5 AND ([DECKSURF_TYPE]=|1| OR [DECKSURF_TYPE]=|5|) AND [WS_SEEDED]>=|6|  AND [LATX_CNT]=0 AND [P3]=|0|

Two errors coming from bamssyst:
- vue.runtime.esm.js:1737 TypeError: Cannot read property 'logicalOperator' of null
    at a.value (CriteriaEditorDialog.vue?9804:179)
- vue.runtime.esm.js:1737 TypeError: Cannot read property 'children' of null
    at a.value (CriteriaEditorDialog.vue?9804:485)
- [x] Examine criteria string to check for malformation
- [x] Add handling for nulls regarding the logicalOperator & children properties of a Criteria object
- [x] Remove invalid / excessive spaces before parsing criteria

**Comment by johnimalmberg** [comment]
The criteria string contains double spaces where there should be single spaces, and has logical operators with spaces between their operands, which should not be present. For example, "[DECK_SEEDED]>= [PREV_DECKSEED]" rather than "[DECK_SEEDED]>=[PREV_DECKSEED]".
After removing these excess spaces with find-and-replace in a text editor, the criteria editor can correctly parse this criteria string.
