### ISSUE TITLE
Investment Editor: Budgets Cleared After Clicking Save

### ISSUE THREAD

**Issue by ppator1** [ARA-Trans/iAM#741]
From Jeff:
•	The biggest issue I have now is that I can’t enter budget amounts for the county maintenance budgets. I added in the 67 new budgets, named them, and added in the criteria. However, now when I try to enter the dollar amounts they disappear after I click save. I was able to enter and change the numbers for Adams and Allegheny County (And all previous MPO budgets), but no more than that. I think the web version might have a budget limit.

**Comment by johnimalmberg** [comment]
Fixed by solution to #742
