### ISSUE TITLE
C# API: Merge Criteria Driven Budgets into Investment API

### ISSUE THREAD

**Issue by ppator1** [ARA-Trans/iAM#757]
Currently the criteria driven budgets API is being called separately from the investments API. This API is only used in conjunction with the investments from the InvestmentEditor in the web app. This adds complexity to keeping track of state/unsaved changes in the web app. These two APIs should be merged into one, namely the criteria driven budgets should be part of the investments API.

**Comment by johnimalmberg** [comment]
Merged into #527
