### ISSUE TITLE
Determine how and where Investment Scenario : Description gets stored

### ISSUE THREAD

**Issue by rbyrne2** [ARA-Trans/iAM#76]
Not going to add much here as this could be a big or small project and no info has been given. This card is a reminder that this will need to be dealt with.

**Comment by ARA-Trans** [comment]
We will need to add a "Description" field to the legacy data architecture. The simulation will need to be tested to ensure that this modification does not cause errors.

When we create investment _libraries_ we will store that information (and retrieve) to/from the firebase database.

**Comment by ARA-Trans** [comment]
SP - 3
