### ISSUE TITLE
Implement Excel report provided from PennDOT

### ISSUE THREAD

**Issue by ARA-Trans** [ARA-Trans/iAM#8]
- [ ] Condition Report Template
- [ ] Budget Required Template (inputs: scenario)
- [ ] Suggested work template (inputs: scenario)
- [ ] Scenario comparison (inputs: list of scenarios)

**Comment by jakedw7** [comment]
Changed due date.  Justin Bruner out with flu.

**Comment by ARA-Trans** [comment]
Received Excel template of desired report. Will implement as is.
